export const BACKGROUND_COLOR = '#000000'
export const TEXT_COLOR_WHITE = '#FFFFFF'
export const STATUSLINE_COLOR = '#FFFFFF'
export const OTHERDAY_LIME = '#7AED7E'
export const INACTIVE_COLOR = '#454444'
export const ERROR_COLOR = '#FF3333'
